# Generated by Django 4.0.10 on 2023-05-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=2)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
